baseURL = 'https://arsekil.github.io/'
languageCode = 'en-us'
title = 'Minden ami Ã©rdekes'
theme = 'mainroad'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
#[[module.imports]]
#path = "github.com/imfing/hextra"
